### ISSUE TITLE
Support Different Quote Types

### ISSUE THREAD

**Issue by gone369** [bryceosterhaus/atom-jest-snippets#5]
It'll be great if there was a dropdown menu in settings to select the different types of quotes that can be used for snippets.
I was thinking to support: 
`
''
` 
`
""
` 
`
``
`
these 3. 
So for example the `desc` snippet can be either:
`describe('', ()=>{})`
`describe("", ()=>{})`
`
describe(``, ()=>{})
`

**Comment by gone369** [comment]
I requested a pull request for this feature.
https://github.com/bryceosterhaus/atom-jest-snippets/pull/6

**Comment by bryceosterhaus** [comment]
Thanks for the contribution! Just released in 2.1.0
